version_variable: 'path/to/__init__.py:__version__'
branch: 'main'
commit_parser:
  style: 'semantic'
commit_version_number:
  major: 'BREAKING CHANGE'
  minor: 'feat'
  patch: 'fix'
changelog:
  generate: true
vcs:
  repository: 'https://github.com/carvalhonm/video-bowser'
