name: Python Semantic Tag

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for semantic versioning

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # Set your Python version here

      - name: Install python-semantic-release
        run: pip install python-semantic-release

      - name: Semantic Release
        run: semantic-release publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
